# STS role and target account
Sts.Role: arn:aws:iam::228697802149:role/admin

# Stack settings
Stack.Name: microtrader-development
Stack.Description: Microtrader Stack - Development

# Override all deletion policies of type AWS::RDS::DBInstance
AWS::RDS::DBInstance:
  DeletionPolicy: Delete

# Database settings
Stack.Inputs.DatabaseName: audit
Stack.Inputs.DatabaseUsername: audit
Stack.Inputs.DatabasePassword: auditpass
